# 1. Basic Array Operations
`Question:` 
`Create a 5x5 NumPy array filled with random integers between 1 and 50. Find the maximum, minimum, and mean of the array.`

In [6]:
import numpy as np
#generate the array
arr = np.random.randint(1,55,(5,5)) 
#generate a 5x5 array with random numbers between 1 and 55
#randint means random integers

#find the max
max = np.max(arr)
min = np.min(arr)
mean = np.mean(arr)

print(arr)
print(f"max: {max}, min: {min}, mean: {mean}")


[[21 22 12 47 24]
 [47 36  2 49  2]
 [13 21 14 38 38]
 [31 19 41 33  6]
 [13 36  3  6 49]]
max: 49, min: 2, mean: 24.92


# 1. Basic Array Operations
`Question:` 
`Create a 5x5 NumPy array filled with random integers between 1 and 50. Find the maximum, minimum, and mean of the array.`